//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hopito.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int id { get; set; }
        public string nom { get; set; }
        public System.DateTime arrivalTime { get; set; }
        public int priorite { get; set; }
        public Nullable<int> idUser { get; set; }
        public int idHopital { get; set; }
    
        public virtual Hopitaux Hopitaux { get; set; }
        public virtual User User { get; set; }
    }
}
