'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Hopitaux
    Public Property id As Integer
    Public Property nom As String
    Public Property adresse As String
    Public Property ville As String
    Public Property province As String
    Public Property codePost As String
    Public Property tel As String

    Public Overridable Property Patients As ICollection(Of Patient) = New HashSet(Of Patient)

End Class
