'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Patient
    Public Property id As Integer
    Public Property nom As String
    Public Property arrivalTime As Date
    Public Property priorite As Integer
    Public Property idUser As Nullable(Of Integer)
    Public Property idHopital As Integer

    Public Overridable Property Hopitaux As Hopitaux
    Public Overridable Property User As User

End Class
